### PR TITLE
Ensure that we can overwrite existing files.

### LINKED ISSUE #287: [macos] Appxmanifest copy failure
## Current behavior

```
/Users/sebastien/.nuget/packages/uno.resizetizer/1.5.0-dev.101/build/Uno.Resizetizer.windows.skia.targets(69,3): error : The file '/.App/obj/Debug/net8.0-desktop/unoresizetizer/m/Package.appxmanifest' already exists. []

```

## Expected behavior

No failure

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

### LINKED ISSUE #292: appx manifest is invalid
## Current behavior

Recent builds of resizetizer may [fail the build](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=128154&view=logs&j=27c58675-674e-5cec-f5db-75e6ea252011&t=e076bf40-55f1-5179-da67-9a21e72ecb1c&l=402):

```
##[error]MakeAppx(0,0): Error : Error info: error C00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 17, Column 140, Reason: The attribute '{[http://schemas.microsoft.com/appx/manifest/foundation/windows10}MaxVersionTested'](http://schemas.microsoft.com/appx/manifest/foundation/windows10%7DMaxVersionTested') on the element '{[http://schemas.microsoft.com/appx/manifest/foundation/windows10}TargetDeviceFamily'](http://schemas.microsoft.com/appx/manifest/foundation/windows10%7DTargetDeviceFamily') is not defined in the DTD/Schema.
MakeAppx : error : Error info: error C00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 17, Column 140, Reason: The attribute '{[http://schemas.microsoft.com/appx/manifest/foundation/windows10}MaxVersionTested'](http://schemas.microsoft.com/appx/manifest/foundation/windows10%7DMaxVersionTested') on the element '{[http://schemas.microsoft.com/appx/manifest/foundation/windows10}TargetDeviceFamily'](http://schemas.microsoft.com/appx/manifest/foundation/windows10%7DTargetDeviceFamily') is not defined in the DTD/Schema. [D:\a\1\s\src\samples\WinUI\Uno.Themes.WinUI.Samples.Windows\Uno.Themes.WinUI.Samples.Windows.csproj]
##[error]MakeAppx(0,0): Error : Package creation failed.
MakeAppx : error : Package creation failed. [D:\a\1\s\src\samples\WinUI\Uno.Themes.WinUI.Samples.Windows\Uno.Themes.WinUI.Samples.Windows.csproj]
##[error]MakeAppx(0,0): Error : 0x80080204 - The specified package format is not valid: The package manifest is not valid.
MakeAppx : error : 0x80080204 - The specified package format is not valid: The package manifest is not valid. [D:\a\1\s\src\samples\WinUI\Uno.Themes.WinUI.Samples.Windows\Uno.Themes.WinUI.Samples.Windows.csproj]
##[error]Process 'msbuild.exe' exited with code '1'.
```

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

### PR DESCRIPTION
**Pull request by dansiegel**
Fixes: #

- fixes #287 
- fixes #292

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

We just rely on File.Move

## What is the new behavior?

If the file currently exists we will first delete the existing one.

### CODE REVIEW

File: src/Resizetizer/src/FileHelper.cs [hunk 1]
```diff
@@ -22,6 +22,12 @@ public static void WriteFileIfChanged(string fileName, TaskLoggingHelper log, Ac
                 if (!File.Exists(fileName)
                     || !File.ReadAllText(fileName).Equals(File.ReadAllText(tempFile)))
                 {
+                    if (File.Exists(fileName))
```
Comment (jeromelaban) [inline src/Resizetizer/src/FileHelper.cs:25]: Let's see if we can regression-test this.

**Review by jeromelaban — APPROVED** [review]

File: src/Resizetizer/src/FileHelper.cs (hunk 1 above)
Comment (dansiegel) [reply src/Resizetizer/src/FileHelper.cs:25]: I've added a Unit Test. Not sure how the integration tests with the incremental builds aren't triggering the condition though.

**Review by jeromelaban — APPROVED** [review]
